### ISSUE TITLE
Avoid publishing emails/passwords to public repos

### ISSUE THREAD

**Issue by ahallhognason** [JeromeJaggi/BirthdayWisher#1]
You may want to move these variables to .env file and not publish them to a public repo (add .env to a .gitignore file)

```python
SENDER_EMAIL
PASSWORD
```

You can read more about [this here](https://www.conjur.org/blog/how-to-scan-github-repositories-for-secrets-credentials-with-open-source/).

**Comment by JeromeJaggi** [comment]
Thank you, good catch! This should not have been there in the first place.
